version: '3.8'

services:
  # Backend API Service
  api:
    build:
      context: ./components/api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - HOST=0.0.0.0
    env_file:
      - ./components/api/.env
    volumes:
      - ./components/api/src:/app/src
      - ./components/api/prisma:/app/prisma
    networks:
      - guepard-network
    restart: unless-stopped

  # Frontend Service
  frontend:
    build:
      context: ./components/frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - VITE_API_BASE_URL=http://localhost:3001/api
      - VITE_APP_NAME=GuepardStore Demo
      - VITE_APP_VERSION=1.0.0
    volumes:
      - ./components/frontend/src:/app/src
    depends_on:
      - api
    networks:
      - guepard-network
    restart: unless-stopped

networks:
  guepard-network:
    driver: bridge
