version: '3.8'

services:
  # Backend API Service
  api:
    build:
      context: ./components/api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - HOST=0.0.0.0
    env_file:
      - ./components/api/.env
    volumes:
      - ./components/api/prisma:/app/prisma
    depends_on:
      - postgres
    networks:
      - guepard-network
    restart: unless-stopped

  # Frontend Service
  frontend:
    build:
      context: ./components/frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - VITE_API_BASE_URL=http://localhost:3001/api
      - VITE_APP_NAME=GuepardStore Demo
      - VITE_APP_VERSION=1.0.0
    depends_on:
      - api
    networks:
      - guepard-network
    restart: unless-stopped

  # PostgreSQL Database (Optional - for local development)
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=guepardstore
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./components/api/prisma/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - guepard-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  guepard-network:
    driver: bridge
